(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.USFinalScores=api;if(typeof document!=='undefined')api.start()})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 const valid=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))&&Number(v)>=0;
 function apply(g,x){if(!g||!x||!(x.final===true||x.status==='final'||/\bfinal\b/i.test(String(x.status?.period||'')))||!valid(x.awayScore)||!valid(x.homeScore))return false;g.awayScore=Number(x.awayScore);g.homeScore=Number(x.homeScore);g.status='final';return true}
 function start(){const saved=new Map(),pending=new Set();const key='usports:verified-finals:2026';const games=()=>typeof GAMES!=='undefined'?GAMES:[];try{for(const x of JSON.parse(localStorage.getItem(key)||'[]'))if(valid(x.awayScore)&&valid(x.homeScore)&&x.status==='final')saved.set(x.id,x)}catch{}
  function save(g){const prior=saved.get(g.id);if(prior?.awayScore===g.awayScore&&prior?.homeScore===g.homeScore)return;saved.set(g.id,{id:g.id,status:'final',awayScore:g.awayScore,homeScore:g.homeScore});try{localStorage.setItem(key,JSON.stringify([...saved.values()]))}catch{}}
  function patch(g){for(const card of document.querySelectorAll('.gameCard[data-game-id="'+CSS.escape(g.id)+'"]')){const scores=card.querySelectorAll('.teamRow .score,.teamRow .at');if(scores.length>=2){if(scores[0].className!=='score')scores[0].className='score';if(scores[0].textContent!==String(g.awayScore))scores[0].textContent=g.awayScore;if(scores[1].className!=='score')scores[1].className='score';if(scores[1].textContent!==String(g.homeScore))scores[1].textContent=g.homeScore}const status=card.querySelector('.gameStatus');if(status){status.classList.add('final');if(status.textContent!=='FINAL')status.textContent='FINAL'}card.querySelectorAll('.awm-card,#us-awm-panel,.schedule-card-pregame').forEach(n=>n.remove());const leaders=window.US_PlayerLeaders?.compact?.(window.US_PLAYER_DATA,g,true,typeof BOX!=='undefined'?BOX[g.id]?.leaders:null)||'';let host=card.querySelector('.schedule-card-leaders');if(leaders){if(!host){host=document.createElement('div');host.className='schedule-card-leaders';(card.querySelector('.gameAction')||card).insertAdjacentElement(card.querySelector('.gameAction')?'beforebegin':'beforeend',host)}if(host.innerHTML!==leaders)host.innerHTML=leaders}else host?.remove();card.setAttribute('onclick',"showGame('"+g.id+"')");const b=card.querySelector('.gameAction button');if(b&&b.textContent!=='BOX SCORE →')b.textContent='BOX SCORE →'}}
  function accept(g,x){if(!apply(g,x))return false;save(g);patch(g);return true}
  function reconcile(){for(const g of games()){const snap=window.V102_LIVE?.selected===g.id?window.V102_LIVE.snap:null;const st=typeof LIVE_STORE!=='undefined'?LIVE_STORE.games?.[g.id]:null;if(snap)accept(g,{status:snap.status,awayScore:snap.game?.awayScore,homeScore:snap.game?.homeScore});if(st)accept(g,{status:{period:st.q},awayScore:st.as,homeScore:st.hs});if(g.status==='final'&&valid(g.awayScore)&&valid(g.homeScore)){save(g);patch(g)}else if(saved.has(g.id))accept(g,saved.get(g.id))}}
  async function poll(){if(document.visibilityState==='hidden')return;reconcile();const today=window.USFeatured?.today()||new Date().toISOString().slice(0,10);const visible=new Set([...document.querySelectorAll('.gameCard[data-game-id]')].map(n=>n.dataset.gameId));const dates=new Set(games().filter(g=>g.date<=today&&(g.date===today||visible.has(g.id)&&(!valid(g.awayScore)||!valid(g.homeScore)))).map(g=>g.date));for(const date of dates){if(pending.has(date))continue;pending.add(date);fetch('/api/scoreboard?date='+date.replace(/-/g,''),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(j=>{for(const x of j?.games||[]){const g=games().find(g=>g.id===x.id);if(g)accept(g,x)}}).catch(()=>{}).finally(()=>pending.delete(date))}}
  const old=window.gameCard;if(typeof old==='function')window.gameCard=function(g){const x=saved.get(g.id);if(x)apply(g,x);return old(g)};
  window.USFinalScores.accept=accept;reconcile();poll();setInterval(reconcile,1000);setInterval(poll,10000);document.addEventListener('visibilitychange',poll);window.addEventListener('online',poll);window.addEventListener('hashchange',()=>setTimeout(poll,0));
 }
 return {valid,apply,start};
});
