(function(){
 const us=!!window.AWM_DATA?.USPORTS,esc=AdvantageModel.esc;
 const base=location.protocol==='file:'?(us?'https://usports-command-centre.vercel.app':'https://college-pro-analytics.vercel.app'):'';
 const state={stats:window.FOOTBALL_STATS||{},rankings:window.US_RANKINGS_SEED,news:us?window.US_NEWS_SEED?.stories||[]:[],checked:'',errors:[],podcasts:[],podcastStatus:'Not yet checked',page:null,category:'passing',league:us?'USPORTS':'NFL'};
 const sources=rows=>(rows||[]).filter(x=>/^https:\/\//.test(x)).map((u,i)=>'<a target="_blank" rel="noopener" href="'+esc(u)+'">Source '+(i+1)+'</a>').join(' · ');
 const table=(heads,rows)=>'<div class="football-scroll"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
 const records=()=>window.USRealtime?.standings?.rows||window.US_STANDINGS_SEED?.rows||[];
 function selectLeague(){return us?'':'<div class="football-filters"><button data-football-league="NFL" aria-pressed="'+(state.league==='NFL')+'">NFL</button><button data-football-league="NCAA" aria-pressed="'+(state.league==='NCAA')+'">NCAA</button></div>'}
 function playerBody(){const d=state.stats[state.league],rows=d?.categories?.[state.category]||[];return selectLeague()+'<p>2026 recorded box-score totals · Data through '+esc(d?.asOf||'unavailable')+' · '+(d?.coveredGames||0)+' games / '+(d?.coveredTeams||0)+' teams covered. These are the top 50 available players in each category; missing box scores can change the order.</p><div class="football-filters">'+['passing','rushing','receiving'].map(c=>'<button data-football-category="'+c+'" aria-pressed="'+(c===state.category)+'">'+c[0].toUpperCase()+c.slice(1)+'</button>').join('')+'</div>'+table(['Player','Team','Games recorded','Yards','TD','Last game','Evidence'],rows.map(p=>[esc(p.name),esc(p.team),p.games,Math.round(p.yards),p.touchdowns,esc(p.lastGame),sources(p.sources)]))}
 function standingsBody(conf){const rows=records().filter(r=>!conf||r.conference===conf);return '<p>2026 official conference records. Updated '+esc(window.USRealtime?.standings?.checkedAt||window.US_STANDINGS_SEED?.checkedAt||'unavailable')+'. Conference totals exclude exhibition games.</p>'+table(['Team','Conference','Played','Wins','Losses','Points for','Points against','Source'],rows.map(r=>[esc(r.name),esc(r.conference),...['g','w','l','pf','pa'].map(k=>r.record?.[k]??'—'),sources([r.url])+(r.stale?' · last verified':'')]))}
 function offenseBody(){const teams=new Map();for(const g of window.US_PLAYER_DATA?.games||[]){if(!g.date.startsWith('2026-'))continue;for(const [id,cats] of Object.entries(g.teams)){if(!cats.passing||!cats.rushing)continue;const t=teams.get(id)||{games:0,passing:0,rushing:0,sources:[]};t.games++;t.passing+=cats.passing.reduce((n,r)=>n+r.yards,0);t.rushing+=cats.rushing.reduce((n,r)=>n+r.yards,0);t.sources.push(g.source);teams.set(id,t)}}return '<h2>Recorded offensive production</h2><p>Totals from complete available 2026 passing and rushing tables; includes any recorded exhibition games. Coverage may differ from official conference records above.</p>'+table(['Team','Box scores','Pass yards','Rush yards','Total yards','Yards/game','Evidence'],[...teams].sort((a,b)=>(b[1].passing+b[1].rushing)/b[1].games-(a[1].passing+a[1].rushing)/a[1].games).map(([id,t])=>[esc(TEAM[id]?.short||id),t.games,t.passing,t.rushing,t.passing+t.rushing,((t.passing+t.rushing)/t.games).toFixed(1),sources(t.sources.slice(-2))]))}
 function rankingsBody(){const r=state.rankings;return '<p>Official U SPORTS poll published '+esc(r?.published||'unavailable')+'. '+sources([r?.source])+'</p>'+table(['Rank','School','Record','Media','Elo points','Total','Previous'],(r?.rows||[]).map(x=>[x.rank,esc(x.name),esc(x.record),x.media,x.elo,x.total,x.previous]))}
 function newsBody(team){const rows=state.news.filter(n=>(!team||n.teams?.includes(team))&&n.date?.startsWith('2026-')&&n.date<=new Date().toISOString().slice(0,10)&&/^https:\/\//.test(n.url));return (!us?selectLeague():'')+'<p>Latest dated football coverage from '+(us?'official school sources':'ESPN')+'. Last successful check: '+esc(state.checked||'saved snapshot')+'.</p>'+rows.filter(n=>us||n.league===state.league).slice(0,40).map(n=>'<article><h3><a href="'+esc(n.url)+'" target="_blank" rel="noopener">'+esc(n.title)+'</a></h3><p>'+esc(n.source)+' · '+esc(n.date)+'</p></article>').join('')+(rows.length?'':'<p>No verified current stories are available yet.</p>')}
 function projectionBody(){const d=window.AWM_DATA[state.league],today=new Date().toISOString().slice(0,10);return selectLeague()+'<p>Advantage Winner Model · Profiles through '+esc(d?.asOf||'unavailable')+'. Open a game from the NFL or College schedule for Gamecast and detailed scenarios.</p>'+(d?.schedule||[]).filter(g=>g.date.slice(0,10)>=today).slice(0,40).map(g=>AdvantageModel.card(AdvantageModel.project(d,{...g,league:state.league}))).join('')}
 function teamBody(slug){const t=TEAM[slug];if(!t)return '<p>Team unavailable.</p>';const row=records().find(r=>r.slug===slug),r=row?.record;const games=GAMES.filter(g=>g.away===slug||g.home===slug).sort((a,b)=>a.date.localeCompare(b.date));return '<h2>'+esc(t.name)+'</h2><p>'+esc(t.conference)+' · '+(r?r.w+' wins, '+r.l+' losses · '+r.pf+' points for, '+r.pa+' against':'Official record unavailable')+'</p>'+sources([row?.url])+'<h3>2026 schedule & Gamecast</h3>'+table(['Date','Opponent','Status','Game'],games.map(g=>[esc(g.date),esc(TEAM[g.away===slug?g.home:g.away]?.name||''),g.status==='final'?esc(g.awayScore+'–'+g.homeScore):esc(g.time||'Pregame'),'<button data-football-game="'+esc(g.id)+'">Open Gamecast</button>']))+'<h3>Latest team news</h3>'+newsBody(slug)}
 async function refreshPodcasts(){try{const j=await json(base+'/api/podcasts');if(!j.ok)throw Error('Channel unavailable');state.podcasts=j.episodes.filter(e=>e.published?.startsWith('2026-')&&/^[\w-]{11}$/.test(e.id));state.podcastStatus='Checked '+j.checkedAt}catch{state.podcastStatus='Channel refresh unavailable; last verified episodes retained'}if(state.page==='podcasts')show('podcasts',true)}
 function podcastBody(){return '<p>Current 2026 episodes from The 55 Podcast’s official channel. '+esc(state.podcastStatus)+'</p>'+state.podcasts.map(e=>'<article><h3>'+esc(e.title)+'</h3><p>'+esc(e.published)+' · '+esc(e.channel)+'</p><a target="_blank" rel="noopener" href="https://www.youtube.com/watch?v='+esc(e.id)+'">Watch episode</a></article>').join('')+(state.podcasts.length?'':'<p>No verified current episodes loaded. <a href="https://www.youtube.com/@atthe55podcast/videos" target="_blank" rel="noopener">Open the official channel</a></p>')}
 function matchupBody(){const a=state.away||'carleton',h=state.home||'guelph',options=selected=>TEAMS.map(t=>'<option value="'+esc(t.slug)+'"'+(t.slug===selected?' selected':'')+'>'+esc(t.name)+'</option>').join('');const d=AWM_DATA.USPORTS;const p=a===h?null:AdvantageModel.project(d,{league:'USPORTS',date:new Date().toISOString().slice(0,10),away:a,home:h,neutral:state.neutral!==false});return '<p>Build a matchup using the same 2026-only Advantage model as the schedule. Profiles through '+esc(d.asOf)+'. Missing profiles remain unavailable.</p><div class="football-filters"><label>Away team <select data-match="away">'+options(a)+'</select></label><label>Home team <select data-match="home">'+options(h)+'</select></label><label>Venue <select data-match="venue"><option value="neutral"'+(state.neutral!==false?' selected':'')+'>Neutral field</option><option value="home"'+(state.neutral===false?' selected':'')+'>Home team’s field</option></select></label></div>'+(p?AdvantageModel.card(p,true,d):'<p>Select two different teams.</p>')}
 function body(page){if(page==='matchup')return matchupBody();if(page==='podcasts')return podcastBody();if(page==='players'||page==='leaders')return playerBody();if(page==='teamstats')return standingsBody()+offenseBody();if(page==='rankings')return rankingsBody();if(page==='media'||page==='news')return newsBody();if(page==='projection')return projectionBody();if(page==='teams')return '<p>All 27 current programs. Select a team for its official record, schedule and latest stories.</p><div class="football-team-grid">'+records().map(r=>'<button data-football-team="'+esc(r.slug)+'"><b>'+esc(r.name)+'</b><br>'+esc(r.conference)+' · '+(r.record?r.record.w+'–'+r.record.l:'Record unavailable')+'</button>').join('')+'</div>';if(page==='conferences')return ['OUA','RSEQ','AUS','CW'].map(c=>'<h2>'+esc(c)+'</h2>'+standingsBody(c)).join('');if(page.startsWith('team='))return teamBody(page.slice(5));return ''}
 const labels={matchup:'Build Matchup',podcasts:'Podcasts',players:'2026 Players',leaders:'2026 Individual Leaders',teamstats:'2026 Team Stats',rankings:'Official National Top 10',teams:'Teams',conferences:'Conferences',media:'Football News & Media',news:'Football News',projection:'Game Predictions'};
 let lastView='';
 function show(page,fromRoute=false){state.page=page;const content='<section class="football-tab"><h1>'+esc(labels[page]||'Team Centre')+'</h1><p class="football-status">'+(state.errors.length?'Some sources are unavailable; last verified data is retained. ':'')+'Live scores keep their existing refresh. Standings/news check every minute; box-score statistics and models refresh on the scheduled data job every two hours.</p>'+body(page)+'</section>';
  if(us){const html=shell(content,page==='players'?'compare':page);if(document.getElementById('app').innerHTML!==html&&lastView!==html){lastView=html;document.getElementById('app').innerHTML=html}if(!fromRoute&&location.hash!=='#'+page)history.pushState(null,'','#'+page)}
  else{let panel=document.getElementById('football-tab-page');if(!panel){panel=document.createElement('main');panel.id='football-tab-page';document.body.append(panel)}panel.style.top=Math.max(56,document.querySelector('.topbar')?.getBoundingClientRect().bottom||56)+'px';if(panel.dataset.key!==content){panel.innerHTML=content;panel.dataset.key=content}}
 }
 function close(){state.page=null;lastView='';document.getElementById('football-tab-page')?.remove()}
 async function json(path){const r=await fetch(path,{cache:'no-cache',signal:AbortSignal.timeout(40000)});if(!r.ok)throw Error('Source unavailable');return r.json()}
 async function refreshFeeds(){if(document.hidden)return;const errors=[];if(us){await Promise.allSettled([['rankings',base+'/api/rankings'],['news',base+'/api/news?days=14']].map(async([key,url])=>{try{const j=await json(url);if(!j.ok)throw Error('Unverified feed');if(key==='rankings'&&j.season===2026)state.rankings=j;else if(key==='news')state.news=j.stories;state.checked=new Date().toISOString()}catch{errors.push(key)}}))}else{await Promise.allSettled([['NFL','nfl'],['NCAA','college-football']].map(async([league,slug])=>{try{const j=await json('https://site.api.espn.com/apis/site/v2/sports/football/'+slug+'/news?limit=30');const rows=(j.articles||[]).map(a=>({title:a.headline,date:a.published?.slice(0,10),url:a.links?.web?.href,source:'ESPN',league}));state.news=[...state.news.filter(n=>n.league!==league),...rows];state.checked=new Date().toISOString()}catch{errors.push(league+' news')}}))}state.errors=errors;if(state.page)show(state.page,true)}
 async function refreshStats(){const leagues=us?['USPORTS']:['NFL','NCAA'];await Promise.allSettled(leagues.map(async l=>{try{const j=await json(base+'/data/player-stats-'+l.toLowerCase()+'.json');if(j.season===2026)state.stats[l]=j}catch{state.errors.push(l+' statistics')}}));try{const w=await json(base+'/data/season-watch.json');for(const l of leagues)if(w[l]?.season===2026)window.SEASON_WATCH[l]=w[l];SeasonWatch.refresh()}catch{}if(state.page)show(state.page,true)}
 async function refreshProfiles(){for(const league of (us?['USPORTS']:['NFL','NCAA']))try{const d=await json(base+'/data/advantage-'+league.toLowerCase()+'.json');if(d.league&&d.league!==league)continue;if(league==='USPORTS'&&d.dataPolicy?.season!==2026)continue;if(d.profiles&&d.model)Object.assign(window.AWM_DATA[league],d)}catch{}if(us)try{const j=await json(base+'/data/verified-results-usports.json');if(j.season===2026){for(const r of j.games){const g=GAMES.find(g=>g.date===r.date&&g.away===r.away&&g.home===r.home);if(g){g.status='final';g.awayScore=r.awayScore;g.homeScore=r.homeScore;g.verifiedSource=r.source}}if(!location.hash||location.hash==='#')updateCal();}}catch{}if(state.page)show(state.page,true);SeasonWatch.refresh()}
 const style=document.createElement('style');style.textContent='.football-tab{background:#101925;color:#eaf0f7;padding:24px;max-width:1250px;margin:20px auto;border:1px solid #293b50;border-radius:14px}.football-tab h1{font-size:30px}.football-tab p{line-height:1.6}.football-status{color:#a7b8cc;font-size:12px}.football-tab a{color:#8eceff}.football-tab article{border-bottom:1px solid #ffffff20;padding:12px 0}.football-scroll{overflow:auto}.football-tab table{width:100%;border-collapse:collapse;white-space:nowrap}.football-tab th,.football-tab td{padding:12px;text-align:left;border-bottom:1px solid #ffffff20}.football-tab button{background:#172b40;color:#eaf0f7;border:1px solid #36516e;border-radius:7px;padding:10px;cursor:pointer}.football-filters{display:flex;gap:8px;margin:18px 0}.football-filters [aria-pressed=true]{border-color:#f5c542;color:#f5c542}.football-team-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}#football-tab-page{position:fixed;left:0;right:0;bottom:0;z-index:28;background:#0b1119;overflow:auto;padding:20px}';document.head.append(style);
 document.addEventListener('change',e=>{const k=e.target.dataset.match;if(!k)return;if(k==='venue')state.neutral=e.target.value==='neutral';else state[k]=e.target.value;lastView='';show('matchup',true)});
 const usLabels={'Leaders':'leaders','Team Stats':'teamstats','Players':'players','Media':'media','Teams':'teams','Conferences':'conferences','Build Matchup':'matchup','Top 10':'rankings','Podcasts':'podcasts'};
 document.addEventListener('click',e=>{if(e.target.closest('[data-watch]')){close();return}const cat=e.target.closest('[data-football-category]');if(cat){state.category=cat.dataset.footballCategory;show(state.page,true);return}const league=e.target.closest('[data-football-league]');if(league){state.league=league.dataset.footballLeague;show(state.page,true);return}const team=e.target.closest('[data-football-team]');if(team){show('team='+team.dataset.footballTeam);return}const game=e.target.closest('[data-football-game]');if(game){close();showGameCast(game.dataset.footballGame);return}const nav=e.target.closest(us?'.nav button':'.mainnav [data-jump]');if(!nav)return;const page=us?usLabels[nav.textContent.trim()]:['players','news','projection'].includes(nav.dataset.jump)?nav.dataset.jump:null;if(page){e.preventDefault();e.stopImmediatePropagation();document.getElementById('watch-page')?.remove();lastView='';show(page);refreshFeeds();refreshStats();if(page==='podcasts')refreshPodcasts()}else close()},true);
 if(us){const oldRoute=window.route;window.route=function(){const p=location.hash.slice(1);if(labels[p]||p.startsWith('team=')){lastView='';show(p,true);return}close();return oldRoute.apply(this,arguments)};for(const [fn,page] of Object.entries({showLeaders:'leaders',showTeamStats:'teamstats',showTeams:'teams',showConferences:'conferences',showMedia:'media',rankingsPage65:'rankings',compare65:'players'}))window[fn]=()=>{lastView='';show(page)};window.matchup72=(a,b,venue)=>{if(a)state.away=a;if(b)state.home=b;state.neutral=venue!=='b';if(venue==='a'){state.away=b;state.home=a;state.neutral=false}lastView='';show('matchup')};window.showTeam=slug=>{lastView='';show('team='+slug)};window.projectedTop65=()=>rankingsBody();}
 const oldHighlights=window.highlights65;if(oldHighlights)window.highlights65=function(){close();oldHighlights();const host=document.querySelector('#app .v65-wrap');if(host)host.insertAdjacentHTML('beforeend','<section class="football-tab"><h2>Latest official coverage</h2><p>Saved clips above remain your local uploads. No verified automatic game-highlight feed is available; these are current source stories.</p>'+newsBody()+'</section>')};
 window.FootballTabs={refresh:refreshFeeds,show,state};refreshFeeds();refreshStats();refreshProfiles();setInterval(refreshProfiles,7200000);setInterval(refreshFeeds,60000);setInterval(refreshStats,300000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshFeeds();refreshStats()}});
})();
