const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'../..'),A=require(path.join(root,'advantage-model.js'));
const leagues=JSON.parse(fs.readFileSync(path.join(root,'data/advantage-leagues.json'))),mode=process.argv[2];
const now=new Date(),bundle={};
for(const league of leagues){
 const file=path.join(root,`data/advantage-${league.toLowerCase()}.json`),d=JSON.parse(fs.readFileSync(file));
 const schedule=league==='USPORTS'?JSON.parse(fs.readFileSync(path.join(root,'data/advantage-schedule-usports.json'))):d.schedule;
 let exact=[];if(league==='NCAA'){const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'advantage-exact.js'),'utf8'),ctx);exact=ctx.window.AWM_EXACT;}
 const localDate=value=>{const bits=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value.length===10?value+'T12:00:00Z':value)).map(p=>[p.type,p.value]));return bits.year+'-'+bits.month+'-'+bits.day;};
 const fromWorkbook=g=>exact.find(p=>p.date===localDate(g.date)&&[g.away.short,g.away.name].map(A.canonical).includes(A.canonical(p.awayName))&&[g.home.short,g.home.name].map(A.canonical).includes(A.canonical(p.homeName)));
 const forecast=g=>fromWorkbook(g)||A.project(d,g);
 d.frozen=d.frozen||{};
 if(mode==='freeze'){
  // Only retain forecasts actually generated by a prior build before the game date.
  const priorFile=path.join(root,`data/forecasts-${league.toLowerCase()}.json`);
  if(fs.existsSync(priorFile))for(const p of JSON.parse(fs.readFileSync(priorFile)).predictions){if(p.modelVersion?.includes('2026')&&p.date<now.toISOString().slice(0,10)&&!d.frozen[p.gameId])d.frozen[p.gameId]=p;}
 }else{
  const predictions=schedule.map(g=>({...forecast(g),gameId:String(g.id)})).filter(p=>p.available);
  const snapshot={createdAt:now.toISOString(),asOf:d.asOf,league,predictions};
  fs.writeFileSync(path.join(root,`data/forecasts-${league.toLowerCase()}.json`),JSON.stringify(snapshot));
  const dir=path.join(root,'data/advantage-snapshots');fs.mkdirSync(dir,{recursive:true});
  const archive=path.join(dir,`${league.toLowerCase()}-${now.toISOString().slice(0,10)}.json`);
  if(!fs.existsSync(archive))fs.writeFileSync(archive,JSON.stringify(snapshot));
 }
 fs.writeFileSync(file,JSON.stringify(d));bundle[league]=d;
}
fs.writeFileSync(path.join(root,'advantage-data.js'),'window.AWM_DATA='+JSON.stringify(bundle).replace(/</g,'\\u003c')+';');
