const HEADERS={
  'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36',
  'Accept-Language':'en-CA,en;q=0.9','Cache-Control':'no-cache','Pragma':'no-cache'
};
function send(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, max-age=30, s-maxage=60, stale-while-revalidate=300');res.end(JSON.stringify(body));}
function dec(s=''){return String(s).replace(/&amp;/g,'&').replace(/&#x2F;/gi,'/').replace(/&#47;/g,'/');}
function one(html,re){const m=String(html||'').match(re);return m?dec(m[1]):'';}
function boolVal(v){return String(v).toLowerCase()==='true';}
function cookieHeader(r){try{if(typeof r.headers.getSetCookie==='function'){const a=r.headers.getSetCookie();if(a?.length)return a.map(x=>x.split(';')[0]).join('; ');}}catch{} const raw=r.headers.get('set-cookie');return raw?raw.split(/,(?=[^;,]+=)/).map(x=>x.split(';')[0]).join('; '):'';}
async function getText(url){const r=await fetch(url,{redirect:'follow',headers:{...HEADERS,'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'}});return {status:r.status,ok:r.ok,text:await r.text(),cookie:cookieHeader(r),url:r.url||url};}
function metaFromHtml(html,page){html=dec(html||'');return {page,event:one(html,/conf\.eventId\s*=\s*['"]([^'"]+)['"]/i),hash:one(html,/conf\.eventIdHashCode\s*=\s*['"]([^'"]+)['"]/i),visitor:one(html,/conf\.visitor\s*=\s*['"]([^'"]*)['"]/i),home:one(html,/conf\.home\s*=\s*['"]([^'"]*)['"]/i),final:boolVal(one(html,/conf\.statusFinal\s*=\s*['"]?([^;'"\n]+)['"]?/i).trim()),visitorLogo:one(html,/conf\.visitorTeamLogo\s*=\s*['"]([^'"]*)['"]/i),homeLogo:one(html,/conf\.homeTeamLogo\s*=\s*['"]([^'"]*)['"]/i)};}
async function fetchLive(meta,cookie=''){if(!meta.event||!meta.hash)return null;const origin=new URL(meta.page).origin,u=new URL('/action/sports/liveupdate',origin);u.searchParams.set('e',meta.event);u.searchParams.set('h',meta.hash);const headers={...HEADERS,'Accept':'application/json,text/plain,*/*','X-Requested-With':'XMLHttpRequest','Referer':meta.page,'Origin':origin};if(cookie)headers.Cookie=cookie;const r=await fetch(u,{headers,redirect:'follow'});const body=await r.text();let j=null;try{j=JSON.parse(body)}catch{}return {status:r.status,json:j};}
async function scanSchedule(scheduleUrl,date){const s=await getText(scheduleUrl);if(!s.ok)return [];const origin=new URL(scheduleUrl).origin;const re=new RegExp(`(?:https?:\\/\\/[^"'<>\\s]+)?\\/sports\\/fball\\/2026-27\\/boxscores\\/${date}_[A-Za-z0-9]+\\.xml`,'gi');const set=new Set();for(const m of s.text.matchAll(re)){let u=m[0];if(u.startsWith('/'))u=origin+u;set.add(u);}return [...set];}
function score(j){const rows=Array.isArray(j?.scores?.score)?j.scores.score:[];for(let i=rows.length-1;i>=0;i--){const a=Number(rows[i]?.vscore),h=Number(rows[i]?.hscore);if(Number.isFinite(a)&&Number.isFinite(h))return {away:a,home:h};}return {away:null,home:null};}
function quarters(j){const rows=Array.isArray(j?.scores?.score)?j.scores.score:[];const away=[0,0,0,0],home=[0,0,0,0];let pv=0,ph=0,seen=false;for(const r of rows){const q=Number(Array.isArray(r.qtr)?r.qtr[0]:r.qtr);const v=Number(r.vscore),h=Number(r.hscore);if(!(q>=1&&q<=4)||!Number.isFinite(v)||!Number.isFinite(h))continue;away[q-1]+=Math.max(0,v-pv);home[q-1]+=Math.max(0,h-ph);pv=v;ph=h;seen=true;}return seen?{away,home}:null;}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/university|universite|ravens|warriors|marauders|gryphons|golden hawks|lancers|mustangs|lions|gaels|gee gees|gee-gees/g,'').replace(/[^a-z0-9]/g,'');}
function matches(meta,away,home){if(!away&&!home)return true;const av=norm(meta.visitor),hm=norm(meta.home),a=norm(away),h=norm(home);return (!a||av.includes(a)||a.includes(av))&&(!h||hm.includes(h)||h.includes(hm));}
function scalarLeaves(root,prefix='',out=[],depth=0){if(depth>5||root==null)return out;if(['string','number'].includes(typeof root)){out.push({path:prefix,value:root});return out;}if(Array.isArray(root))return out;if(typeof root!=='object')return out;for(const [k,v] of Object.entries(root)){if(/player|roster|individual/i.test(k))continue;scalarLeaves(v,prefix?`${prefix}.${k}`:k,out,depth+1);}return out;}
function teamObjects(j){const arr=Array.isArray(j?.team)?j.team:(j?.team&&typeof j.team==='object'?Object.values(j.team):[]);return arr.filter(x=>x&&typeof x==='object');}
function pickTeam(arr,side){return arr.find(o=>String(o.vh||o.side||o.homeAway||'').toUpperCase()===(side==='away'?'V':'H'))||arr[side==='away'?0:1]||null;}
function pick(leaves,patterns){for(const re of patterns){const x=leaves.find(r=>re.test(r.path));if(x&&x.value!==''&&x.value!=null)return x.value;}return null;}
function compactStats(j){const arr=teamObjects(j),a=pickTeam(arr,'away'),h=pickTeam(arr,'home');if(!a||!h)return [];const al=scalarLeaves(a),hl=scalarLeaves(h);const defs=[
 ['First Downs',[/first.*down/i]],['Rushing Yards',[/rush.*yd/i,/rushing.*yard/i]],['Passing Yards',[/pass.*yd/i,/passing.*yard/i]],['Total Offense',[/total.*off/i,/offense.*yd/i,/total.*yard/i]],['Passing',[/pass.*(?:comp|cmp).*att/i,/comp.*att/i]],['Rushing Attempts',[/rush.*att/i]],['Third Down',[/third.*down/i,/3rd.*down/i]],['Fourth Down',[/fourth.*down/i,/4th.*down/i]],['Turnovers',[/turnover/i]],['Penalties',[/penalt/i]],['Sacks',[/sack/i]],['Time of Possession',[/time.*possession/i,/poss.*time/i]]
 ];
 const out=[];for(const [label,pats] of defs){const av=pick(al,pats),hv=pick(hl,pats);if(av!=null||hv!=null)out.push([label,av??'—',hv??'—']);}return out;
}
function plays(j){const a=Array.isArray(j?.plays?.play)?j.plays.play:[];return a.slice(-24).reverse().map(p=>({q:String(p.qtr||p.quarter||''),clock:String(p.clock||''),description:String(p.description||p.desc||p.text||'')})).filter(x=>x.description);}
function drives(j){const a=Array.isArray(j?.drives?.drive)?j.drives.drive:[];return a.slice(-16).reverse().map(d=>({team:String(d.team||''),plays:d.plays??'',yards:d.yards??d.yds??'',result:String(d.result||''),time:String(d.time||d.top||'')}));}
module.exports=async function handler(req,res){
 if(req.method!=='GET')return send(res,405,{ok:false,error:'GET only'});
 const date=String(req.query.date||'').replace(/\D/g,'').slice(0,8);if(date.length!==8)return send(res,400,{ok:false,error:'date=YYYYMMDD required'});
 const away=String(req.query.away||''),home=String(req.query.home||''),detail=String(req.query.detail||'')==='1';
 const scheduleUrls=['https://en.usports.ca/sports/fball/2026-27/schedule','https://oua.ca/sports/fball/2026-27/schedule'];
 let pages=[];for(const u of scheduleUrls){try{pages.push(...await scanSchedule(u,date));}catch{}}pages=[...new Set(pages)].slice(0,30);
 const games=[];
 for(const page of pages){try{const b=await getText(page);if(!b.ok)continue;const meta=metaFromHtml(b.text,page);if(!meta.event||!meta.hash||!matches(meta,away,home))continue;const live=await fetchLive(meta,b.cookie);const j=live?.json;if(!j||j.error)continue;const sc=score(j);games.push({page,boxId:(page.match(/\/([^/]+)\.xml$/)||[])[1]||'',visitor:meta.visitor,home:meta.home,visitorLogo:meta.visitorLogo,homeLogo:meta.homeLogo,final:meta.final||String(j?.status?.complete||'').toUpperCase()==='Y',awayScore:sc.away,homeScore:sc.home,...(detail?{quarters:quarters(j),teamStats:compactStats(j),plays:plays(j),drives:drives(j),lastUpdated:String(j?.network?.lastUpdated||'')}:{})});if(detail&&away&&home)break;}catch{}}
 send(res,200,{ok:true,date,count:games.length,games});
};
