const schedules=require('../data/advantage-schedule-usports.json');
const known=require('../data/game-recaps.json');
const sites={carleton:'https://goravens.ca',guelph:'https://gryphons.ca',waterloo:'https://athletics.uwaterloo.ca',laurier:'https://laurierathletics.com',windsor:'https://golancers.ca',western:'https://westernmustangs.ca',york:'https://yorkulions.ca',toronto:'https://varsityblues.ca',queens:'https://gogaelsgo.com',ottawa:'https://geegees.ca',bishops:'https://gaiters.ca',mcgill:'https://mcgillathletics.ca',concordia:'https://stingers.ca',laval:'https://rougeetor.ulaval.ca',montreal:'https://carabins.umontreal.ca',sherbrooke:'https://www.usherbrooke.ca',acadia:'https://acadiaathletics.ca','mount-allison':'https://mountiepride.ca','saint-marys':'https://smuhuskies.ca',stfx:'https://goxgo.ca',calgary:'https://godinos.com',ubc:'https://gothunderbirds.ca',manitoba:'https://gobisons.ca',saskatchewan:'https://huskies.usask.ca',regina:'https://www.reginacougars.com',alberta:'https://bearsandpandas.ca'};
const names=require('../data/usports-teams.json');
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;|&rsquo;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
async function get(url,origin){const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(6000),redirect:'follow'});if(!r.ok||new URL(r.url).hostname!==new URL(origin).hostname)return '';return r.text();}
function discover(html,g,origin){const t=names.find(t=>t.slug===g.away),tokens=[g.away,t?.short,t?.name].filter(Boolean).map(norm),start=new Date(g.date+'T00:00:00Z').getTime();const candidates=[];
 for(const m of html.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)){const tag=k=>m[1].match(new RegExp('<'+k+'[^>]*>([\\s\\S]*?)<\\/'+k+'>','i'))?.[1]?.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1')||'';const title=clean(tag('title')),url=clean(tag('link')),date=new Date(tag('pubDate'));if(!Number.isFinite(date.getTime())||date.getTime()<start||date.getTime()>start+3*86400000)continue;if(!tokens.some(t=>norm(title).includes(t))||!/football|fball/i.test(url+' '+title)||/preview|ahead|set to|tickets|week ahead/i.test(title))continue;try{if(new URL(url).hostname!==new URL(origin).hostname)continue}catch{continue}candidates.push({url,date:date.toISOString().slice(0,10)});}
 return candidates;
}
async function lookup(g){const origin=sites[g.home];if(!origin)return null;const xml=await get(origin+'/rss.aspx?path=football',origin);const candidates=discover(xml,g,origin);
 for(const candidate of candidates.slice(0,2)){const html=await get(candidate.url,origin);if(!html||!/Game Recap|game-recap|recap/i.test(html))continue;const match=html.match(/<meta\b[^>]*(?:name|property)=["'](?:description|og:description)["'][^>]*content=["']([^"']*)["']/i);const excerpt=clean(match?.[1]);if(!excerpt)continue;return {...candidate,source:names.find(t=>t.slug===g.home)?.name||g.home,summary:excerpt.split(/\s+/).slice(0,20).join(' ')+'…',paraphrased:false};}
 return null;
}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=3600');if(req.method!=='GET')return res.status(405).json({error:'GET only'});const id=String(req.query.game||''),g=schedules.find(g=>g.id===id);if(!g)return res.status(404).json({error:'Unknown game'});try{const recap=known[id]||await lookup(g);res.status(200).json({gameId:id,recap})}catch{res.status(200).json({gameId:id,recap:null})}};
module.exports.discover=discover;
