const teams=require('../data/usports-teams.json');
const saved=require('../data/verified-results-usports.json');
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases=new Map(teams.flatMap(t=>['slug','short','name','abbr'].map(k=>[norm(t[k]),t.slug])));
for(const [a,s] of Object.entries({'St. Francis Xavier':'stfx','St. Marys':'saint-marys','Mt. Allison':'mount-allison','Universite de Montreal':'montreal'}))aliases.set(norm(a),s);
function team(s){const n=norm(s);return aliases.get(n)||teams.find(t=>n.startsWith(norm(t.short)))?.slug}
function decode(s){return String(s||'').replace(/&eacute;/gi,'é').replace(/&egrave;/gi,'è').replace(/&ocirc;/gi,'ô').replace(/&#(x[0-9a-f]+|\d+);/gi,(_,n)=>String.fromCodePoint(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n))).replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/&(?:apos|rsquo);/g,"'").replace(/&quot;/g,'"')}
function text(s){return decode(s.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim())}
// Balanced elements: nested participant markup must not truncate scores or names.
function elements(html,cls){const out=[];const re=/<\/?([\w-]+)\b[^>]*>/g;let start=-1,depth=0,m;while((m=re.exec(html))){const close=m[0][1]==='/';if(start>=0){if(close)depth--;else if(!/\/$/.test(m[0].slice(0,-1))&&!/^(img|br|hr|input|meta|link)$/i.test(m[1]))depth++;if(depth===0){out.push(html.slice(start,re.lastIndex));start=-1}}else if(!close&&new RegExp('class=["\'][^"\']*\\b'+cls+'\\b').test(m[0])){start=m.index;depth=1}}return out}
function parse(html,date){return elements(html,'event-row').flatMap(row=>{const p=elements(row,'list-events-participants');if(p.length!==2)return [];const ids=p.map(x=>{const n=elements(x,'team-name')[0]||'';return team(decode(n.match(/title=(["'])(.*?)\1/)?.[2]||text(n).replace(/^(at|vs\.?)\s+/i,'')))});const label=text(elements(row,'cal-status')[0]||'');const scores=p.map(x=>{const s=text(elements(x,'team-result')[0]||'');return /^\d+$/.test(s)?Number(s):null});if(!ids.every(Boolean)||!/\bfinal\b/i.test(label)||scores.some(s=>s===null))return [];return [{id:date+'-'+ids.join('-'),date,away:ids[0],home:ids[1],awayScore:scores[0],homeScore:scores[1],status:'final',final:true,source:'https://en.usports.ca/sports/fball/composite?d='+date,...(row.match(/href=["']([^"']*\/boxscores\/[^"']+)["']/i)?{boxscore:new URL(decode(row.match(/href=["']([^"']*\/boxscores\/[^"']+)["']/i)[1]),'https://en.usports.ca').href}:{})}]})}
const lastGood=new Map();
async function handler(req,res){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.statusCode=405;return res.end(JSON.stringify({ok:false}))}const raw=String(req.query.date||'').replace(/\D/g,'');if(!/^2026\d{4}$/.test(raw)){res.statusCode=400;return res.end(JSON.stringify({ok:false,error:'2026 date required'}))}const date=raw.slice(0,4)+'-'+raw.slice(4,6)+'-'+raw.slice(6),results=new Map((lastGood.get(date)||[]).map(g=>[g.id,g]));for(const g of saved.games.filter(g=>g.date===date))results.set(date+'-'+g.away+'-'+g.home,{...g,id:date+'-'+g.away+'-'+g.home,status:'final',final:true});let fresh=false;try{const r=await fetch('https://en.usports.ca/sports/fball/composite?d='+date,{headers:{'User-Agent':'Mozilla/5.0','Cache-Control':'no-cache'},signal:AbortSignal.timeout(8000)});if(r.ok){const html=await r.text();if(/event-row/.test(html)){fresh=true;for(const g of parse(html,date))results.set(g.id,g)}}}catch{}const games=[...results.values()];lastGood.set(date,games);res.end(JSON.stringify({ok:true,date,games,fresh}))}
module.exports=handler;module.exports.parse=parse;module.exports.team=team;
